name: Build and push docker images

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - chore/*
      - security/*
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        if: github.repository == 'lexiforest/curl-impersonate'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check if tag is present
        id: check_tag
        run: |
          if [[ "${GITHUB_REPOSITORY}" == "lexiforest/curl-impersonate" ]]; then
            echo "docker_namespace=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          else
            echo "docker_namespace=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          fi

          if [[ "${GITHUB_REF}" =~ ^refs/tags/v ]]; then
            echo "push_image=true" >> $GITHUB_ENV
            echo "image_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "push_image=false" >> $GITHUB_ENV
            echo "image_tag=latest" >> $GITHUB_ENV
          fi

      - name: Build debian docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/debian.dockerfile
          push: ${{ github.repository == 'lexiforest/curl-impersonate' && env.push_image == 'true' && 'true' || 'false' }}
          tags: |
            ${{ env.docker_namespace }}/curl-impersonate:${{ env.image_tag }}
            ${{ env.docker_namespace }}/curl-impersonate:latest

      - name: Build alpine docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpine.dockerfile
          push: ${{ github.repository == 'lexiforest/curl-impersonate' && env.push_image == 'true' && 'true' || 'false' }}
          tags: |
            ${{ env.docker_namespace }}/curl-impersonate:${{ env.image_tag }}-alpine
            ${{ env.docker_namespace }}/curl-impersonate:alpine
